version: 2.1
orbs:
  codecov: codecov/codecov@3.2.3
executors:
  docker-executor:
    docker:
      - image: cimg/python:3.10
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/project
  docker-executor-py35:
    docker:
      - image: cimg/python:3.5
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/project
  docker-executor-py36:
    docker:
      - image: cimg/python:3.6
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/project
  docker-executor-py37:
    docker:
      - image: cimg/python:3.7
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/project
  docker-executor-py38:
    docker:
      - image: cimg/python:3.8
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/project
  docker-executor-py39:
    docker:
      - image: cimg/python:3.9
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/project

commands:
  save_pip_cache:
    steps:
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1.0-pip-cache-{{ checksum "requirements/requirements-test.lock.txt" }}
  restore_pip_cache:
    steps:
      - restore_cache:
          keys:
            - v1.0-pip-cache-{{ checksum "requirements/requirements-test.lock.txt" }}
  save_py_venv_cache:
    steps:
      - save_cache:
          paths:
            - ~/.venv
          key: v1.0-py-venv-{{ checksum "requirements/requirements-test.lock.txt" }}
  restore_py_venv_cache:
    steps:
      - restore_cache:
          keys:
            - v1.0-py-venv-{{ checksum "requirements/requirements-test.lock.txt" }}
  save_project_workspace:
    steps:
      - persist_to_workspace:
          root: ~/
          paths:
            - project/
            - .venv/
  restore_project_workspace:
    steps:
      - attach_workspace:
          at: ~/

jobs:
  setup_project:
    executor: docker-executor
    environment:
      CRYPTOGRAPHY_DONT_BUILD_RUST: 1
    steps:
      - checkout
      - restore_pip_cache
      - restore_py_venv_cache
      - run: python -m venv --copies ~/.venv
      - run: source ~/.venv/bin/activate && make install_test
      - save_pip_cache
      - save_py_venv_cache
      - save_project_workspace
  flake8:
    executor: docker-executor
    steps:
      - restore_project_workspace
      - run: source ~/.venv/bin/activate && make flake8
  mypy:
    executor: docker-executor
    steps:
      - restore_project_workspace
      - run: source ~/.venv/bin/activate && make mypy
  pylint:
    executor: docker-executor
    steps:
      - restore_project_workspace
      - run: source ~/.venv/bin/activate && make pylint
  docscheck:
    executor: docker-executor
    steps:
      - restore_project_workspace
      - run: source ~/.venv/bin/activate && make check_docs
  packagecheck:
    executor: docker-executor
    steps:
      - restore_project_workspace
      - run: source ~/.venv/bin/activate && make check_package
  test:
    executor: docker-executor
    steps:
      - restore_project_workspace
      - run: source ~/.venv/bin/activate && make test ARGS="-v --cov --cov-report xml"
  test-tox:
    parameters:
      py:
        type: string
      django:
        type: string
    executor: docker-executor-py<< parameters.py >>
    environment:
      TOXENV: py<< parameters.py >>-django<< parameters.django >>
    steps:
      - restore_project_workspace
      - restore_pip_cache
      - run: pip install tox
      - run: tox

workflows:
  workflow:
    jobs:
      - setup_project
      - flake8:
          requires:
            - setup_project
      - mypy:
          requires:
            - setup_project
      - pylint:
          requires:
            - setup_project
      - docscheck:
          requires:
            - setup_project
      - packagecheck:
          requires:
            - setup_project
      - test:
          requires:
            - flake8
            - mypy
            - setup_project
          post-steps:
            - codecov/upload
      - test-tox:
          name: test-tox-py39-django40
          py: "39"
          django: "40"
          requires:
            - test
      - test-tox:
          name: test-tox-py39-django32
          py: "39"
          django: "32"
          requires:
            - test
      - test-tox:
          name: test-tox-py38-django31
          py: "38"
          django: "31"
          requires:
            - test
          filters:
            branches:
              only: master
      - test-tox:
          name: test-tox-py37-django30
          py: "37"
          django: "30"
          requires:
            - test
          filters:
            branches:
              only: master
      - test-tox:
          name: test-tox-py37-django22
          py: "37"
          django: "22"
          requires:
            - test
      - test-tox:
          name: test-tox-py36-django21
          py: "36"
          django: "21"
          requires:
            - test
          filters:
            branches:
              only: master
      - test-tox:
          name: test-tox-py36-django20
          py: "36"
          django: "20"
          requires:
            - test
          filters:
            branches:
              only: master
